authors/urls.py
from django.urls import path
from authors import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.registerView, name='register'),
    path('register/create/', views.registerCreate, name='create'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/recipe/create/', views.DashboardRecipe.as_view(), name='dashboard_recipe_create'),
    path('dashboard/recipe/delete/', views.DashboardRecipeDelete.as_view(), name='dashboard_recipe_delete'),
    path('dashboard/recipe/<int:id>/edit/', views.DashboardRecipe.as_view(), name='dashboard_recipe_edit'),
    path('profile/edit', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/<int:id>/', views.ProfileView.as_view(), name='profile'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('recipes.urls')),
    path("authors/", include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('', views.RecipeListViewHome.as_view(), name='home'),
    path('recipes/search', views.RecipeListViewSearch.as_view(), name='search'),
    path('recipes/tags/<slug:slug>', views.RecipeListViewTag.as_view(), name='tag'),
    path('recipes/category/<int:category_id>/', views.RecipeListViewCategory.as_view(), name='category'),
    path('recipes/<int:pk>/', views.RecipeDetailView.as_view(), name='recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.contenttypes.fields import GenericRelation
from tag.models import Tag

from collections import defaultdict
from django.core.exceptions import ValidationError

class Category(models.Model):
    name = models.CharField(max_length=65)

    # A class Meta é uma ferramenta poderosa e flexível no Django, usada para definir metadados e configurações adicionais tanto em modelos quanto em formulários.
    # No contexto do Django, metadados são usados para fornecer informações adicionais e configurações sobre modelos, formulários, e outros componentes
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class RecipeManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True)
    
class Recipe(models.Model):
    objects = RecipeManager()
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # Ao deletar uma categoria o atributo category recebe Null
    # blank=True equivale a permitir não receber valor no formulário
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True, default='')

    # class Meta:
    #     ordering = ['id']
    #     verbose_name = 'Recipe'
    #     verbose_name_plural = 'Recipes'

    def __str__(self):
        return self.title
 
    # Adiciona um link para a view do site no admin e serve como um atalho de reverse para alguma url, nesse caso: recipes:recipe
    def get_absolute_url(self):
        return reverse('recipes:recipe', args=(self.id, ))

    def save(self, *args, **kwargs):
        if not self.slug:
            count = Recipe.objects.filter(title=self.title).count()
            if count != 0:
                slug = f'{slugify(self.title)}-{count}' 
            else:
                slug = slugify(self.title)
            self.slug = slug

        return super().save(*args, **kwargs)

    # Validação customizada
    def clean(self, *args, **kwargs):
        error_messages = defaultdict(list)

        recipes_from_db = Recipe.objects.filter(
            title__iexact=self.title
        ).first()

        if recipes_from_db:
            if recipes_from_db.pk != self.pk:
                error_messages['title'].append('Já existe uma receita com esse título')

        if error_messages:
            raise ValidationError(error_messages)

authors/forms/recipe_form.py
from django import forms
from recipes.models import Recipe
from django.core.exceptions import ValidationError
from utils.django_forms import add_widget_attr

class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        add_widget_attr(self.fields.get('preparation_steps'), 'class', 'col-md-12')

    class Meta:
        model = Recipe
        fields = ['title', 'description', 'preparation_time', 'preparation_time_unit', 'servings', 'servings_unit',
                    'preparation_steps', 'cover'  
                ]

        labels = {
            'title': 'Titulo',
            'description': 'Descrição',
            'preparation_time': 'Tempo de preparo',
            'preparation_time_unit': 'Tempo',
            'servings': 'Quantidade de pessoas servidas',
            'servings_unit': 'Forma de servir',
            'preparation_steps': 'Modo de preparo',
            'cover': 'Imagem',
        }

        widgets = {
            'cover': forms.FileInput(attrs={'class': 'col-md-12'}),
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                )
            ),
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Pedaços', 'Pedaços'),
                )
            )
        }

    def clean_title(self):
        title = self.cleaned_data.get('title')

        if len(title) < 5:
            raise ValidationError('O título deve ter no minímo 5 caracteres', code='min_length')
        
        return title

    def clean_description(self):
        description = self.cleaned_data.get('description')

        if len(description) < 5:
            raise ValidationError('A descrição deve ter no minímo 5 caracteres', code='min_length')
        
        return description

    def clean_servings(self):
        servings = int(self.cleaned_data.get('servings'))

        if servings < 1:
            raise ValidationError(
                'Precisa servir no mínimo 1 pessoa',
                code='invalid'
            )
        
        return servings
        
    def clean(self):
        data = super().clean()

        preparation_time = int(self.cleaned_data.get('preparation_time'))
        preparation_time_unit = self.cleaned_data.get('preparation_time_unit')

        if preparation_time < 5 and preparation_time_unit == 'Minutos':
            raise ValidationError({
                'preparation_time': 'O tempo de preparo deve ter no mínimo 5 minutos'
            }, code='invalid')
        
        return data
    

recipes/views/all.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator
from utils.pagination import make_pagination_range, make_pagination
from django.contrib import messages

from recipes.models import Recipe
import os

PER_PAGE = int(os.environ.get('PER_PAGE'))

def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/home.html', {'recipes': page_obj, 'pagination_range': pagination_range})

def category(request, category_id):
    # recipes = Recipe.objects.filter(category__id=category_id, is_published=True)
    recipes = get_list_or_404(Recipe.objects.filter(category__id=category_id, is_published=True))
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/category.html', {'recipes': page_obj, 'pagination_range': pagination_range, 'title': recipes[0].category.name})

def recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)
    return render(request, 'recipes/recipe-view.html', {'is_details': True, 'recipe': recipe})

def search(request):
    # A funcão strip remove espaços em branco no inicio e fim
    search_term = request.GET.get('q', '').strip()
    
    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        # A função Q() muda a condicional para OR
        Q(
            Q(title__icontains=search_term) | 
            Q(description__icontains=search_term)
        ),
        is_published=True
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/search.html', 
        {'page_title': f'Pequisa por "{search_term}"', 
        'search_term': search_term, 
        'recipes': page_obj, 'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}'
        })

recipes/views/recipe_view.py
from typing import Any
from django.db.models.query import QuerySet
from django.views.generic import ListView, DetailView
from recipes.models import Recipe
from utils.pagination import make_pagination
from django.db.models import Q
from django.http import Http404

import os
PER_PAGE = int(os.environ.get('PER_PAGE'))

class RecipeListBaseView(ListView):
    
    model = Recipe
    context_object_name = 'recipes'
    ordering = ('-id')
    # template_name = 'recipes/home.html'
    
    def get_queryset(self):
        qs = super().get_queryset()

        qs = qs.filter(is_published=True)

        #Melhora a perfomance. Na mesma consulta já busca o usuário e categoria com join
        qs.select_related('author', 'category')
        qs.prefetch_related('tags', 'author__profile')

        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        page_obj, pagination_range = make_pagination(self.request, ctx.get('recipes'), PER_PAGE)

        ctx.update({'recipes': page_obj, 'pagination_range': pagination_range})

        return ctx


class RecipeListViewHome(RecipeListBaseView):
    template_name = 'recipes/home.html'


class RecipeListViewCategory(RecipeListBaseView):
    template_name = 'recipes/category.html'

    def get_queryset(self):
        qs = super().get_queryset()

        qs = qs.filter(category__id=self.kwargs.get('category_id'))

        return qs
    

class RecipeListViewSearch(RecipeListBaseView):
    template_name = 'recipes/search.html'

    def get_queryset(self):
        qs = super().get_queryset()

        search_term = self.request.GET.get('q', '').strip()

        qs = qs.filter( Q(
            Q(title__icontains=search_term) | 
            Q(description__icontains=search_term)
        ))

        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        search_term = self.request.GET.get('q', '').strip()
        
        ctx.update( 
            {
            'page_title': f'Pequisa por "{search_term}"', 
            'search_term': search_term, 
            'additional_url_query': f'&q={search_term}'
            }
        )

        return ctx


class RecipeDetailView(DetailView):    
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/recipe-view.html'

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)

        if obj.is_published == False:
            raise Http404()

        return obj

    def get_context_data(self, *args, **kwargs: Any):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({'is_details': True})
        
        return ctx


class RecipeListViewTag(RecipeListBaseView):
    template_name = 'recipes/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)

        qs = qs.filter(tags__slug=self.kwargs.get('slug'))

        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        
        ctx.update( 
            {
            'page_title': self.kwargs.get('slug'), 
            }
        )

        return ctx
        

recipes/templates/recipes/includes/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
    <div class="recipe-cover">
        <img src="{{ recipe.cover.url }}" alt="Temporário">
    </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">{{ recipe.title }}</h2>
    </div>

    <div class="recipe-author">
        {% if recipe.author is not None %}
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author.profile %}
                <a href="{% url 'authors:profile' recipe.author.profile.id %}">
            {% endif %}

            {% if recipe.author.firstname %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
                {{ recipe.author.username }}
            {% endif %}
            
            {% if recipe.author.profile %}
                </a>
            {% endif %}

        </span>
        {% endif %}

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            <!-- |date é um filtro de template do django que formata a data/hora de acordo com o formato especificado. -->
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
        </span>

        {% if recipe.category is not None %}
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magni fugiat commodi ullam quas modi.
            Ea cumque labore veniam, sequi corrupti quas beatae fuga alias quae, vero dicta accusamus
            aliquam in!</p>
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_details is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_details is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>

        {% if recipe.tags.all %}
        <p>Tags:
            {% for tag in recipe.tags.all %}
                    <a href="{% url 'recipes:tag' tag.slug %}"> {{tag.name}}</a>
            {% endfor %}
        </p>
        {% endif %}

    {% endif %}

</div>